[
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@/components/ui/alert-dialog' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 13,
    startColumn: 8,
    endLineNumber: 13,
    endColumn: 38,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@/components/ui/form' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 30,
    startColumn: 8,
    endLineNumber: 30,
    endColumn: 30,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@/components/ui/popover' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 37,
    startColumn: 8,
    endLineNumber: 37,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@/components/ui/slider' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 46,
    startColumn: 24,
    endLineNumber: 46,
    endColumn: 48,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@/components/ui/switch' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 47,
    startColumn: 24,
    endLineNumber: 47,
    endColumn: 48,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@/components/ui/use-toast' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 49,
    startColumn: 23,
    endLineNumber: 49,
    endColumn: 50,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@hookform/resolvers/zod' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 51,
    startColumn: 29,
    endLineNumber: 51,
    endColumn: 54,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@radix-ui/react-icons' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 52,
    startColumn: 30,
    endLineNumber: 52,
    endColumn: 53,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module 'date-fns' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 53,
    startColumn: 24,
    endLineNumber: 53,
    endColumn: 34,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module '@/components/ui/calendar' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 54,
    startColumn: 26,
    endLineNumber: 54,
    endColumn: 52,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module 'next-auth/react' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 56,
    startColumn: 28,
    endLineNumber: 56,
    endColumn: 45,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message:
      "Cannot find module 'react-hook-form' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 58,
    startColumn: 25,
    endLineNumber: 58,
    endColumn: 42,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "2307",
    severity: 8,
    message: "Cannot find module 'zod' or its corresponding type declarations.",
    source: "ts",
    startLineNumber: 59,
    startColumn: 20,
    endLineNumber: 59,
    endColumn: 25,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7031",
    severity: 8,
    message: "Binding element 'field' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 291,
    startColumn: 28,
    endLineNumber: 291,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7031",
    severity: 8,
    message: "Binding element 'field' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 307,
    startColumn: 28,
    endLineNumber: 307,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7031",
    severity: 8,
    message: "Binding element 'field' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 323,
    startColumn: 28,
    endLineNumber: 323,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7031",
    severity: 8,
    message: "Binding element 'field' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 343,
    startColumn: 28,
    endLineNumber: 343,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7031",
    severity: 8,
    message: "Binding element 'field' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 371,
    startColumn: 28,
    endLineNumber: 371,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7031",
    severity: 8,
    message: "Binding element 'field' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 392,
    startColumn: 28,
    endLineNumber: 392,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7031",
    severity: 8,
    message: "Binding element 'field' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 414,
    startColumn: 28,
    endLineNumber: 414,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7006",
    severity: 8,
    message: "Parameter 'value' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 422,
    startColumn: 41,
    endLineNumber: 422,
    endColumn: 46,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7031",
    severity: 8,
    message: "Binding element 'field' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 433,
    startColumn: 28,
    endLineNumber: 433,
    endColumn: 33,
  },
  {
    resource:
      "/d:/myprojetc/alquran-website/alquran-website/components/dashboard/dashboard-form.tsx",
    owner: "typescript",
    code: "7006",
    severity: 8,
    message: "Parameter 'date' implicitly has an 'any' type.",
    source: "ts",
    startLineNumber: 460,
    startColumn: 38,
    endLineNumber: 460,
    endColumn: 42,
  },
];
